name: micro_serve
description: A Flutter package initializes an HTTP server to handle HTTP requests.

version: 1.0.3

homepage: https://mithun1st.blogspot.com/
repository: https://www.github.com/mithun1st/

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  # lints: ^3.0.0
